# Generated by Django 4.1.3 on 2024-07-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_uploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
